#!/bin/bash
# shellcheck disable=SC2001
set -euo pipefail

cmdname="$(basename "${BASH_SOURCE[0]}")"
version=0.0.3

report-log() {
  echo "$1" > /dev/stderr
}

report-error() {
  echo "$cmdname: $1" > /dev/stderr
  exit 1
}

usage() {
  echo "Usage: $cmdname create user/name or $cmdname update name.rb"
}

get-latest-json() {
  target=$1
  api_url="https://api.github.com/repos/$target/releases/latest"
  report-log "Fetching $api_url"
  json=$(curl -s "$api_url")
  if ! echo "$json" | grep '"message".*"Not Found"' > /dev/null; then
    echo "$json"
    return
  fi
  api_url="https://api.github.com/repos/$target/tags"
  report-log "Fetching $api_url"
  json=$(curl -s "$api_url")
  if ! echo "$json" | grep '"message".*"Not Found"' > /dev/null; then
    echo "$json"
    return
  fi
  report-error "failed to get the latest release"
}

find-latest-version() {
  json=$1
  version=$(echo "$json" | sed -n '/"tag_name"/s/^.*: *"\(.*\)".*$/\1/gp' | head -n1)
  if [[ $version != "" ]]; then
    echo "${version##v}"
    return
  fi
  version=$(echo "$json" | sed -n '/"name"/s/^.*: *"\(.*\)".*$/\1/gp' | head -n1)
  if [[ $version != "" ]]; then
    echo "${version##v}"
    return
  fi
  report-error "failed to get version: $json"
}

find-download-url() {
  target=$1
  json=$2
  url=$(echo "$json" | sed -n '/browser_download_url.*darwin/s/^.*: *"\(.*\)".*$/\1/gp' | head -n1)
  if [[ $url != "" ]]; then
    echo "$url"
    return
  fi
  if echo "$json" | grep '"zipball_url"' > /dev/null; then
    name=$(echo "$json" | sed -n '/"name"/s/^.*: *"\(.*\)".*$/\1/gp' | head -n1)
    echo "https://github.com/$target/archive/$name.zip"
    return
  fi
  report-error "failed to get download url: $json"
}

get-target-name() {
  target=$1
  echo "${target##*/}"
}

get-sha256() {
  url=$1
  report-log "Fetching $url"
  shasum=$(curl -s -L "$url" | sha256sum | cut -f1 -d ' ')
  report-log "Got sha256sum: $shasum"
  echo "$shasum"
}

create() {
  target=$1
  name=$(get-target-name "$target")
  formula_name=$(echo "$name" | perl -pe 's/(^|-)([a-z])/uc($2)/ge')
  output="$name.rb"
  report-log "Creating $output"
  json=$(get-latest-json "$target")
  version=$(find-latest-version "$json")
  report-log "Found version $version"
  url=$(find-download-url "$target" "$json")
  sha256=$(get-sha256 "$url")
  homepage="https://github.com/$target"
  git_url="https://github.com/$target.git"
  cat > "$output" <<EOF
class $formula_name < Formula
  homepage '$homepage'
  version '$version'
  url '$url'
  sha256 '$sha256'
  head '$git_url'

  def install
    bin.install '$name'
  end

  test do
    system "#{bin}/$name", '--version'
  end
end
EOF
  report-log "Created $output"
}

get-target-from-formula() {
  target_file=$1
  sed -n "/homepage.*github.com/s/^.*github.com\/\\(.*\\)'.*/\\1/gp" < "$target_file" | head -n1
}

get-version-from-formula() {
  target_file=$1
  sed -n "/^ *version /s/^.*version *'\\(.*\\)'.*/\\1/gp" < "$target_file" | head -n1
}

update() {
  output=$1
  report-log "Updating $output"
  target=$(get-target-from-formula "$output")
  if [[ $target == "" ]]; then
    report-error "failed to find target: $output"
  fi
  current_version=$(get-version-from-formula "$output")
  if [[ $current_version == "" ]]; then
    report-error "failed to find version: $output"
  fi
  name=$(get-target-name "$target")
  json=$(get-latest-json "$target")
  version=$(find-latest-version "$json")
  if [[ $current_version == "$version" ]]; then
    report-log "Already the latest version $version"
    exit 0
  fi
  report-log "Found version $version"
  url=""
  outtmp=$(mktemp -t "$name.XXXXXXXX")
  trap 'rm -rf $outtmp' EXIT SIGHUP SIGINT SIGQUIT SIGTERM
  while IFS= read -r line; do
    if echo "$line" | grep '^ *version ' > /dev/null; then
      line=$(echo "$line" | sed 's/[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}/'"$version"'/')
    elif echo "$line" | grep '^ *url ' > /dev/null; then
      line=$(echo "$line" | sed 's/[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}/'"$version"'/')
      url=$(echo "$line" | sed "s/^.*'\\(.*\\)'.*$/\\1/")
    elif echo "$line" | grep '^ *sha256 ' > /dev/null; then
      if [[ $url == "" ]]; then
        report-error "url not found: $line"
      fi
      sha256=$(get-sha256 "$url")
      line=$(echo "$line" | sed "s/'.*'/'$sha256'/")
    fi
    echo "$line"
  done < "$output" > "$outtmp"
  mv "$outtmp" "$output"
  report-log "Updated $output"
}

main() {
  subcmd=$1
  case "$subcmd" in
    create)
      create "$2"
      ;;
    update)
      update "$2"
      ;;
    --version|-v)
      echo "$cmdname $version"
      ;;
    *)
      usage
      report-error "unknown command: $subcmd"
      ;;
  esac
}

if [[ $# -lt 1 ]]; then
  usage
  report-error "specify command"
elif [[ $1 != "-"* && $# -lt 2 ]]; then
  usage
  report-error "specify target"
elif [[ $# -gt 2 ]]; then
  usage
  report-error "too many arguments"
fi

main "$1" "${2:-}"
