name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Test
      run: |
        ./formulate create itchyny/mackerel-plugin-battery
        ./formulate create itchyny/mackerel-plugin-dice
        ./formulate create itchyny/gojq
        ./formulate create itchyny/miv
        ./formulate create itchyny/git-branch-name
        ./formulate update git-branch-name.rb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Show version
      run: ./formulate --version
